name: picbox
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # design
  material_design_icons_flutter: ^4.0.5045
  ubuntu_font_flutter: ^0.0.1
  flare_flutter: ^2.0.2
  transparent_image: ^1.0.0
  pansy_ui:
    git: git://github.com/oneLab-Projects/pansy_ui.git

  # localizations
  flutter_localizations:
    sdk: flutter
  easy_localization: ^2.1.0+0

  # bloc
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.1
  provider: ^4.0.4

  # network
  chopper: ^3.0.2
  json_annotation: ^3.0.1

  # db
  shared_preferences: ^0.5.6+3
  flutter_secure_storage: ^3.3.2

  # convert
  built_value: ^7.0.9
  built_collection: ^4.3.2

  # compare
  equatable: ^1.1.1

  # data
  logger: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  chopper_generator: ^3.0.4
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - resources/flare/
    - resources/lang/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-R.ttf
        - asset: packages/ubuntu_font_flutter/Ubuntu-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/Ubuntu-BI.ttf
          weight: 700
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-L.ttf
          weight: 300
        - asset: packages/ubuntu_font_flutter/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-M.ttf
          weight: 500
        - asset: packages/ubuntu_font_flutter/Ubuntu-MI.ttf
          weight: 500
          style: italic
    - family: Ubuntu Mono
      fonts:
        - asset: packages/ubuntu_font_flutter/UbuntuMono-R.ttf
        - asset: packages/ubuntu_font_flutter/UbuntuMono-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/UbuntuMono-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/UbuntuMono-BI.ttf
          weight: 700
          style: italic
    - family: Ubuntu Condensed
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-C.ttf
